backend:
  name: github
  repo: lucadebort/lucadb
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: project
    label: Project
    folder: projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: seoTitle, label: SEOTitle }
      - { name: seoDesc, label: SEODesc }  
      - { name: body, label: Body, widget: markdown }